# Generated by Django 4.2.23 on 2025-09-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_type', '0003_remove_fueltype_usage_in_cars'),
        ('car', '0002_alter_ceo_company_carmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='company',
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carmodel')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_type.fueltype')),
            ],
        ),
    ]
