# Generated by Django 4.2.23 on 2025-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_type', '0003_remove_fueltype_usage_in_cars'),
        ('car', '0003_remove_carmodel_company_cardetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.ManyToManyField(related_name='car_models', to='fuel_type.fueltype'),
        ),
    ]
