# Generated by Django 4.2.23 on 2025-09-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_ceo_company_carmodel'),
        ('fuel_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='usage_in_cars',
            field=models.ManyToManyField(related_name='fuel_types', to='car.carmodel'),
        ),
    ]
