# Generated by Django 4.2.23 on 2025-09-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_type', '0002_fueltype_usage_in_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueltype',
            name='usage_in_cars',
        ),
    ]
